-- Schema for Pet table
CREATE TABLE IF NOT EXISTS pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL
);

-- Test data for Pet
INSERT INTO pet (name, owner_name) VALUES ('Max', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Bella', 'Sarah Johnson');
INSERT INTO pet (name, owner_name) VALUES ('Charlie', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Luna', 'Emily Davis');
INSERT INTO pet (name, owner_name) VALUES ('Rocky', 'Michael Brown');

-- Schema for Visit table
CREATE TABLE IF NOT EXISTS visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    clinic VARCHAR(255) NOT NULL,
    pet_id BIGINT NOT NULL,
    FOREIGN KEY (pet_id) REFERENCES pet(id)
);

-- Test data for Visit
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-15 09:30:00', 'Downtown Clinic', 1);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-18 14:00:00', 'North Branch', 1);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-10 10:15:00', 'East Side Clinic', 2);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-20 11:45:00', 'Downtown Clinic', 2);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-12 16:30:00', 'North Branch', 3);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-22 08:00:00', 'East Side Clinic', 4);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-17 13:20:00', 'Downtown Clinic', 4);
INSERT INTO visit (date_time, clinic, pet_id) VALUES ('2025-11-21 15:00:00', 'North Branch', 4);
