-- Drop existing tables to ensure clean schema
DROP TABLE IF EXISTS visit;
DROP TABLE IF EXISTS vet;
DROP TABLE IF EXISTS pet;

-- Schema for Pet table
CREATE TABLE IF NOT EXISTS pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL
);

-- Test data for Pet
INSERT INTO pet (name, owner_name) VALUES ('Max', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Bella', 'Sarah Johnson');
INSERT INTO pet (name, owner_name) VALUES ('Charlie', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Luna', 'Emily Davis');
INSERT INTO pet (name, owner_name) VALUES ('Rocky', 'Michael Brown');

-- Schema for Vet table
CREATE TABLE IF NOT EXISTS vet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specialty VARCHAR(255) NOT NULL
);

-- Test data for Vet
INSERT INTO vet (id, name, specialty) VALUES (1, 'Dr. Sarah Martinez', 'Surgery');
INSERT INTO vet (id, name, specialty) VALUES (2, 'Dr. James Chen', 'Dentistry');
INSERT INTO vet (id, name, specialty) VALUES (3, 'Dr. Emily Rodriguez', 'General Practice');
INSERT INTO vet (id, name, specialty) VALUES (4, 'Dr. Michael Thompson', 'Cardiology');

-- Schema for Visit table
CREATE TABLE IF NOT EXISTS visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    clinic VARCHAR(255) NOT NULL,
    pet_id BIGINT NOT NULL,
    vet_id BIGINT,
    FOREIGN KEY (pet_id) REFERENCES pet(id),
    FOREIGN KEY (vet_id) REFERENCES vet(id)
);

-- Test data for Visit
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-15 09:30:00', 'Downtown Clinic', 1, 1);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-18 14:00:00', 'North Branch', 1, 3);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-10 10:15:00', 'East Side Clinic', 2, 2);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-20 11:45:00', 'Downtown Clinic', 2, 1);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-12 16:30:00', 'North Branch', 3, 3);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-22 08:00:00', 'East Side Clinic', 4, 2);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-17 13:20:00', 'Downtown Clinic', 4, 1);
INSERT INTO visit (date_time, clinic, pet_id, vet_id) VALUES ('2025-11-21 15:00:00', 'North Branch', 4, 4);
