-- Schema for Pet table
CREATE TABLE IF NOT EXISTS pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL
);

-- Test data for Pet
INSERT INTO pet (name, owner_name) VALUES ('Max', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Bella', 'Sarah Johnson');
INSERT INTO pet (name, owner_name) VALUES ('Charlie', 'John Smith');
INSERT INTO pet (name, owner_name) VALUES ('Luna', 'Emily Davis');
INSERT INTO pet (name, owner_name) VALUES ('Rocky', 'Michael Brown');
